# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_pic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='image',
            field=models.ImageField(upload_to='gallery_images'),
        ),
    ]
